[tool.poetry]
name = "webcrawler"
version = "0.1.0"
description = "Intelligent web crawler for documentation assembly"
authors = ["CloudCurio <dev@cloudcurio.cc>"]
license = "MIT"
readme = "README.md"
packages = [{include = "webcrawler", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = "^3.12.4"
beautifulsoup4 = "^4.13.4"
urllib3 = "^2.5.0"
pydantic = "^2.11.5"
sqlalchemy = "^2.0.41"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^1.0.0"
black = "^25.1.0"
mypy = "^1.15.0"
pylint = "^3.3.7"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
show_error_codes = true

[tool.pylint.messages_control]
disable = [
    "C0111",
    "R0903",
    "C0103"
]

[tool.pylint.format]
max-line-length = 100

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=webcrawler --cov-report=term-missing -v"
