[tool.poetry]
name = "mcp_server"
version = "0.1.0"
description = "Message Control Program server for AI-powered web crawling and document assembly"
authors = ["CloudCurio <dev@cloudcurio.cc>"]
readme = "README.md"
packages = [{include = "mcp_server", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.12"
uvicorn = "^0.34.2"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.23"}
alembic = "^1.13.0"
asyncpg = "^0.29.0"
psycopg2-binary = "^2.9.9"
playwright = "^1.40.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pydantic = {extras = ["email"], version = "^2.5.2"}
redis = {extras = ["hiredis"], version = "^5.0.1"}
python-multipart = "^0.0.6"
aiohttp = "^3.9.1"
openai = "^1.3.5"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-asyncio = "^0.23.2"
pytest-cov = "^4.1.0"
black = "^23.11.0"
mypy = "^1.7.1"
ruff = "^0.1.6"
httpx = "^0.25.2"
asgi-lifespan = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
strict_optional = true

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "B", "I", "UP"]
ignore = []

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=mcp_server --cov-report=term-missing -v"
asyncio_mode = "auto"

[project]
name = "mcp-server"
version = "0.1.0"
description = "Message Control Program server for AI-powered web crawling and document assembly"
authors = [
    {name = "CloudCurio",email = "dev@cloudcurio.cc"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "playwright (>=1.52.0,<2.0.0)",
    "openai (>=1.82.1,<2.0.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "pydantic (>=2.11.5,<3.0.0)",
    "uvicorn (>=0.34.2,<0.35.0)",
    "aiohttp (>=3.12.4,<4.0.0)",
    "asyncio (>=3.4.3,<4.0.0)",
    "python-multipart (>=0.0.20,<0.0.21)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
